### ISSUE TITLE
pc lags if i select more than 1 thread

### ISSUE THREAD

**Issue by CarlsbergFTW** [mikrohash/isf-jclient#7] opened 2018-02-08 18:41 UTC
Hello,

Whenever i select more than 1 thread, pc gets very slow and sometimes it stalls for 10-15 seconds.
This did not happen on the previous version of iotaspam and i do believe that i can squeze ALOT more out of this cpu/config.

W10
i7-6700k - no overclock
maximus viii impact (mini ITX)
32GB  cosrsair 2400
no video.

Thank you for creating this tool.
In case you need other information let me know. I'm more than willing to provide data and help fix this.

**Comment by laubblaeser** [comment] 2018-02-08 18:58
This issue is a duplicate of https://github.com/mikrohash/isf-jclient/issues/6 . 
Please add your request over there for consolidation of issues.

**Comment by vuapo-eth** [comment] 2018-02-24 19:49
Fixed in v1.0.4

**Closed as completed** 2018-04-29 16:50 UTC
Labels: duplicate
