### ISSUE TITLE
Invalid json, maybe caused by API or encoding?

### ISSUE THREAD

**Issue by tjw0418** [mikrohash/isf-jclient#10] opened 2018-02-09 15:17 UTC
![image](https://user-images.githubusercontent.com/15151194/36035449-e7032228-0df1-11e8-9574-91da014549f2.png)

![image](https://user-images.githubusercontent.com/15151194/36035684-9d470fa4-0df2-11e8-8eaf-706d722c2778.png)

![image](https://user-images.githubusercontent.com/15151194/36035287-63603aaa-0df1-11e8-9d66-8c2e4b3f8ee3.png)

java version: 1.8.0_161
os: win 7

**Comment by tjw0418** [comment] 2018-02-09 15:39
It happens when I run "java -jar isf-jclient-1.0.3.jar"

**Comment by vuapo-eth** [comment] 2018-02-09 20:07
Thank you for the report. This seems to be a rare error caused by the https://iotanode.host/ API. We will work on that.

**Comment by vuapo-eth** [comment] 2018-02-24 19:49
Fixed in v1.0.4

**Closed as completed** 2018-04-29 16:51 UTC
Labels: bug
